# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('header', '0007_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header.employee')),
            ],
        ),
    ]
