# Generated by Django 4.1.7 on 2023-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20)),
                ('e_email', models.CharField(max_length=20)),
                ('e_qualification', models.CharField(max_length=20)),
                ('e_experience', models.BigIntegerField()),
                ('e_gender', models.CharField(max_length=20)),
                ('e_dob', models.CharField(max_length=20)),
                ('e_password', models.CharField(max_length=20)),
                ('e_phone', models.BigIntegerField()),
            ],
        ),
    ]
