# Generated by Django 4.1.7 on 2023-03-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addleader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header.employee')),
            ],
        ),
    ]
