# Generated by Django 4.1.7 on 2023-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_addproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='leader',
            new_name='leader_name',
        ),
    ]
