# Generated by Django 4.1.7 on 2023-03-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_rename_leader_addproject_leader_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='leader_name',
            new_name='leadername',
        ),
    ]
